//Declarative Style//

def args = '-var 'aws_region=params.REGION' -var 'instance_ami=params.AMI' -var 'key_pair=params.KEY''

pipeline {
    agent any
 

    options {
        ansiColor('xterm')
        timestamps()
    }

    parameters {
        string(name: 'REGION', description: 'Region to deploy')
        string(name: 'AMI', description: 'AMI ID to deploy')
        string(name: 'KEY', description: 'KEYPAIR to deploy')
    }

    stages {
        stage("Terraform init") {
          steps {
              dir('jenkins-terraform') {
              sh 'ls -lrt'    
              sh "terraform init"
             } //dir
           }  // steps
        } //Stage   
        stage("Terraform plan") {
          steps {
              dir('jenkins-terraform') {
              script{
                sh "terraform plan $args"
              } //Script   
             } //dir
           }  // steps
        } //Stage  
        stage("Terraform apply") {
          steps {
              script {
              dir('jenkins-terraform') {
              def USER_INPUT = input message: 'Please confirm to apply', ok:'Next', parameters: [string(name: 'Apply', defaultvalue: 'apply', description: 'Click to Apply')]
              env.APPLY = USER_INPUT
              sh "terraform ${env.APPLY} $args --auto-approve"
              } //dir
            } //Script
          }  //steps
        } //Stage 
    } //All stages     
} //Pipeline